package modelo.entidad;
// Generated 10-17-2021 03:36:10 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String descripcion;
     private Long precio;
     private Long existencia;
     private String fechallegada;

    public Productos() {
    }

    public Productos(String nombre, String descripcion, Long precio, Long existencia, String fechallegada) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.precio = precio;
       this.existencia = existencia;
       this.fechallegada = fechallegada;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Long getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Long precio) {
        this.precio = precio;
    }
    public Long getExistencia() {
        return this.existencia;
    }
    
    public void setExistencia(Long existencia) {
        this.existencia = existencia;
    }
    public String getFechallegada() {
        return this.fechallegada;
    }
    
    public void setFechallegada(String fechallegada) {
        this.fechallegada = fechallegada;
    }




}


